### ISSUE TITLE
Research UI Component Frameworks

### ISSUE THREAD

**Issue by connorielliott** [PowerSynth/front-end#32]
We need to decide on a UI library to use. Our team is considering the following options: Blueprint UI, Fluent UI, and React Bootstrap. We need to determine which library would be the best fit for our project based on factors such as ease of use, customization options, community support, and documentation.

To start our research, here are some useful links for each library:

- [Blueprint UI](https://blueprintjs.com/docs/)
- [Fluent UI](https://developer.microsoft.com/en-us/fluentui#/get-started/web)
- [React Bootstrap](https://react-bootstrap.github.io/)

Please share any additional resources or insights you may have on these libraries, or any others we should consider. Let's discuss the pros and cons of each option and come to a consensus on the best choice for our project.

Additionally, once we have chosen a UI library, we will need to add documentation to the repo wiki to ensure that all team members can use the library effectively.

**Comment by RailgunZx** [comment]
Here's a brief summery of my research thus far:

## Fluent UI
Fluent UI is probably the easiest component library to use and the documentation provides examples of every component which includes code snippets. It's not the biggest component library, but a lot of what it does provide looks very relevant to our project needs. The biggest advantage of Fluent UI is probably its ease of use.
#### Pros
- Very easy to use
- Good documentation by Microsoft
- Example code for every component
- Simple theming system for specifying how the entire project looks

#### Cons
- Not as powerful as the other libraries
- Relatively new, so may not have as much support online as other libraries

#### Resources
- [Microsoft Fluent UI Website](https://developer.microsoft.com/en-us/fluentui#/get-started/web)
- [Fluent UI Github Wiki](https://github.com/microsoft/fluentui/wiki)
- [Theme Builder](https://fluentuipr.z22.web.core.windows.net/heads/master/theming-designer/index.html)

## React-Bootstrap
React-Bootstrap is a very widely used and comprehensive component library which is built off of Bootstrap. It has a lot of support and a large variety of components to choose from, but the documentation is not as detailed as it could be. It also contains a lot of components which are probably not useful for our project which might make it a little difficult to find what you are looking for.
#### Pros
- Integrates well with React and can be easily customized to fit the design needs of the project.
- Lots of community support
- Large variety of components

#### Cons
- Not entirely synergistic with our project design 
- Documentation is not as detailed
- Components and styles are not as customizable as Fluent UI
- Possibly a higher learning curve than the other libraries

#### Resources
- [Documentation Page](https://react-bootstrap.github.io/getting-started/introduction/)
- [Online React Sandbox](https://codesandbox.io/examples/package/react-bootstrap)

## Blueprint
Blueprint is a smaller library but the components are designed with desktop application functionality in mind which makes them highly relevant to our project. The functionality and styling of the components are also very customizable. The documentation is easy to use and gives comprehensive examples of all components and their properties.

**In my opinion, this is absolutely the best library because of how well the design philosophy of its components matches our project needs. Blueprint is also fairly easy to use.**
#### Pros
- Excellent documentation
- Highly interactable component examples
- Components best match our project needs
- Many components are very technical and offer a great deal of customization
- Integrates well with React

#### Cons
- Newer library, so might not have as much community support
- Not every part of the documentation contains code snippets
- Not as many components as other libraries

#### Resources
- [Blueprint Documentation](https://blueprintjs.com/docs/)

**Comment by connorielliott** [comment]
Great work. My vote is blueprint

**Comment by kevin-german** [comment]
My vote is for blueprint as well.

**Comment by atejedag** [comment]
I guess I'll also vote blueprint.

**Comment by RailgunZx** [comment]
Blueprint wins.
